spring:
  r2dbc:
    url: r2dbc:postgresql://ep-odd-sun-a56iuqcm-pooler.us-east-2.aws.neon.tech/db_prs1?sslmode=require
    username: db_prs1_owner
    password: npg_1sQejrO2hupA

  kafka:
    bootstrap-servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="53QBHPHGWMCFCWXG" password="tXwcS2Hk15Q2wFmIHg6CXeZF3i9KpC2H75ioGr/v7SZLbnvTbiUcy68I1T8p2n3A";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: springboot-group-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/security-prs1

server:
  port: 8081
